import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

import 'l10n/app_localizations.dart';
import 'src/features/localization/presentation/cubit/locale_cubit.dart';
import 'src/features/offers/data/repositories/offers_repository.dart';
import 'src/features/offers/presentation/bloc/offers_bloc.dart';
import 'src/features/account/presentation/account/bloc/account_bloc.dart';
import 'src/features/main/presentation/pages/splash_page.dart';
import 'src/core/constants/app_colors.dart';
import 'src/core/network/api_client.dart';
import 'src/features/account/data/repositories/auth_repository.dart';
import 'src/core/preferences/pref_store.dart';
import 'src/features/home/data/repositories/home_repository.dart';
import 'src/features/home/presentation/bloc/home_bloc.dart';
import 'src/features/cart/data/repositories/cart_repository.dart';
import 'src/features/cart/presentation/bloc/cart_bloc.dart';
import 'src/features/cart/presentation/bloc/cart_event.dart';

import 'src/core/routing/app_router.dart';
import 'src/core/services/deep_link_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await PrefStore.init();
  final deepLinkService = DeepLinkService();
  await deepLinkService.init();
  runApp(MyApp(deepLinkService: deepLinkService));
}

class MyApp extends StatelessWidget {
  final HomeRepository? homeRepository;
  final OffersRepository? offersRepository;
  final CartRepository? cartRepository;
  final AuthRepository? authRepository;
  final DeepLinkService? deepLinkService;

  const MyApp({
    super.key,
    this.homeRepository,
    this.offersRepository,
    this.cartRepository,
    this.authRepository,
    this.deepLinkService,
  });

  @override
  Widget build(BuildContext context) {
    // Provide both cubits and blocs at the top level
    return MultiRepositoryProvider(
      providers: [
        RepositoryProvider<OffersRepository>(
          create: (context) => offersRepository ?? OffersRepositoryImpl(apiClient: ApiClient()),
        ),
        RepositoryProvider<HomeRepository>(
          create: (context) => homeRepository ?? HomeRepositoryImpl(apiClient: ApiClient()),
        ),
        RepositoryProvider<CartRepository>(
          create: (context) => cartRepository ?? CartRepositoryImpl(apiClient: ApiClient()),
        ),
      ],
      child: MultiBlocProvider(
        providers: [
          BlocProvider<LocaleCubit>(
            create: (context) => LocaleCubit(),
          ),
          BlocProvider<CartBloc>(
            create: (context) => CartBloc(
              cartRepository: context.read<CartRepository>(),
            ),
          ),
          BlocProvider<OffersBloc>(
            create: (context) => OffersBloc(
              offersRepository: context.read<OffersRepository>(),
            ),
          ),
          BlocProvider<HomeBloc>(
            create: (context) => HomeBloc(
              homeRepository: context.read<HomeRepository>(),
            ),
          ),
          BlocProvider<AccountBloc>(
            lazy: false,
            create: (context) => AccountBloc(
              authRepository: authRepository ?? AuthRepositoryImpl(
                apiClient: ApiClient(),
              ),
            ),
          ),
        ],
        child: const AppView(),
      ),
    );
  }
}

class AppView extends StatelessWidget {
  const AppView({super.key});

  @override
  Widget build(BuildContext context) {
    // Watch LocaleCubit to rebuild app when locale changes
    final locale = context.watch<LocaleCubit>().state;

    return MaterialApp.router(
      routerConfig: AppRouter.router,
      title: 'Qupon',
      debugShowCheckedModeBanner: false,
      locale: locale,
      // Declare supported locales
      supportedLocales: const [
        Locale('en'),
        Locale('ar'),
      ],
      // Localization delegates generated by flutter gen-l10n
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: AppColors.primary,
          primary: AppColors.primary,
        ),
        fontFamily: 'Outfit', // Premium layout default font
      ),
    );
  }
}

